#!/usr/bin/env python3
"""
翻译 ALL_DOCS.md 中的英文标题为简体中文
"""

import re
from pathlib import Path

DOCS_FILE = Path(__file__).parent / "ALL_DOCS.md"

TRANSLATIONS = {
    # 通用术语 - 完整标题匹配
    "Quick setup (beginner)": "快速设置（初学者）",
    "Quick setup": "快速设置",
    "Goals": "目标",
    "Config writes": "配置写入",
    "Config quick map": "配置快速映射",
    "Config": "配置",
    "Architecture (who owns what)": "架构（各组件职责）",
    "Architecture": "架构",
    "Getting a phone number (two modes)": "获取电话号码（两种模式）",
    "Dedicated number (recommended)": "专用号码（推荐）",
    "Personal number (fallback)": "个人号码（备选）",
    "Number sourcing tips": "号码获取技巧",
    "Why Not Twilio?": "为什么不用 Twilio？",
    "Login + credentials": "登录 + 凭证",
    "Inbound flow (DM + group)": "入站流程（私信 + 群组）",
    "Personal-number mode (fallback)": "个人号码模式（备选）",
    "Read receipts": "已读回执",
    "Message normalization (what the model sees)": "消息标准化（模型看到的内容）",
    "Groups": "群组",
    "Reply delivery (threading)": "回复发送（线程）",
    "Acknowledgment reactions (auto-react on receipt)": "确认反应（收到后自动反应）",
    "Agent tool (reactions)": "代理工具（反应）",
    "Limits": "限制",
    "Outbound send (text + media)": "出站发送（文本 + 媒体）",
    "Voice notes (PTT audio)": "语音消息（PTT 音频）",
    "Media limits + optimization": "媒体限制 + 优化",
    "Heartbeats": "心跳",
    "Reconnect behavior": "重连行为",
    "Logs + troubleshooting": "日志 + 故障排除",
    "Troubleshooting (quick)": "故障排除（快速）",
    "Troubleshooting": "故障排除",
    "How it works": "工作原理",
    "How to create your own bot": "如何创建自己的机器人",
    "Get the ids (guild/user/channel)": "获取 ID（服务器/用户/频道）",
    "4) Get the ids (guild/user/channel)": "4) 获取 ID（服务器/用户/频道）",
    "Token": "令牌",
    "Allowlist + channel routing": "白名单 + 频道路由",
    "Verify it works": "验证是否正常",
    "6) Verify it works": "6) 验证是否正常",
    "Capabilities & limits": "功能与限制",
    "Retry policy": "重试策略",
    "Tool action defaults": "工具操作默认值",
    "Reply tags": "回复标签",
    "Tool actions": "工具操作",
    "Safety & ops": "安全与运维",
    "Socket mode (default)": "Socket 模式（默认）",
    "Setup": "设置",
    "User token (optional)": "用户令牌（可选）",
    "Token usage": "令牌用法",
    "History context": "历史上下文",
    "Manifest (optional)": "清单（可选）",
    "Scopes (current vs optional)": "权限范围（当前 vs 可选）",
    "Bot token scopes (required)": "机器人令牌权限（必需）",
    "User token scopes (optional, read-only by default)": "用户令牌权限（可选，默认只读）",
    "Not needed today (but likely future)": "目前不需要（但未来可能需要）",
    "Reply threading": "回复线程",
    "Per-chat-type threading": "按聊天类型的线程",
    "Manual threading tags": "手动线程标签",
    "Sessions + routing": "会话 + 路由",
    "DM security (pairing)": "私信安全（配对）",
    "Group policy": "群组策略",
    "Delivery targets": "发送目标",
    "Security notes": "安全说明",
    "Notes": "说明",
    "What it is": "这是什么",
    "Requirements": "要求",
    "Setup (fast path)": "设置（快速路径）",
    "Remote/SSH variant (optional)": "远程/SSH 变体（可选）",
    "Access control (DMs + groups)": "访问控制（私信 + 群组）",
    "How it works (behavior)": "工作原理（行为）",
    "Media + limits": "媒体 + 限制",
    "Addressing / delivery targets": "寻址/发送目标",
    "Overview": "概述",
    "Prerequisites": "前提条件",
    "Installation": "安装",
    "Configuration": "配置",
    "Usage": "使用方法",
    "Examples": "示例",
    "Reference": "参考",
    "FAQ": "常见问题",
    "See also": "另请参阅",
    "Related": "相关内容",
    "Next steps": "下一步",
    "Summary": "总结",
    "Introduction": "简介",
    "Getting started": "入门",
    "Basic usage": "基本用法",
    "Advanced usage": "高级用法",
    "Best practices": "最佳实践",
    "Common issues": "常见问题",
    "Known issues": "已知问题",
    "Features": "功能特性",
    "Benefits": "优势",
    "Comparison": "对比",
    "Migration": "迁移",
    "Upgrade": "升级",
    "Security": "安全",
    "Privacy": "隐私",
    "Performance": "性能",
    "Optimization": "优化",
    "Debugging": "调试",
    "Testing": "测试",
    "Deployment": "部署",
    "Monitoring": "监控",
    "Logging": "日志",
    "Alerts": "告警",
    "Notifications": "通知",
    "Events": "事件",
    "Handlers": "处理器",
    "Middleware": "中间件",
    "Plugins": "插件",
    "Extensions": "扩展",
    "Modules": "模块",
    "Components": "组件",
    "Services": "服务",
    "Providers": "提供商",
    "Adapters": "适配器",
    "Connectors": "连接器",
    "Integrations": "集成",
    "Channels": "通道",
    "Platforms": "平台",
    "Environments": "环境",
    "Variables": "变量",
    "Secrets": "密钥",
    "Tokens": "令牌",
    "Keys": "密钥",
    "Certificates": "证书",
    "Permissions": "权限",
    "Roles": "角色",
    "Users": "用户",
    "Teams": "团队",
    "Organizations": "组织",
    "Projects": "项目",
    "Workspaces": "工作区",
    "Sessions": "会话",
    "Contexts": "上下文",
    "Memory": "记忆",
    "History": "历史",
    "Messages": "消息",
    "Conversations": "对话",
    "Threads": "线程",
    "Replies": "回复",
    "Reactions": "反应",
    "Attachments": "附件",
    "Files": "文件",
    "Images": "图片",
    "Videos": "视频",
    "Audio": "音频",
    "Documents": "文档",
    "Links": "链接",
    "Commands": "命令",
    "Actions": "操作",
    "Tools": "工具",
    "Skills": "技能",
    "Agents": "代理",
    "Models": "模型",
    "Prompts": "提示词",
    "Templates": "模板",
    "Formats": "格式",
    "Schemas": "模式",
    "Types": "类型",
    "Interfaces": "接口",
    "Classes": "类",
    "Functions": "函数",
    "Methods": "方法",
    "Properties": "属性",
    "Parameters": "参数",
    "Arguments": "参数",
    "Options": "选项",
    "Flags": "标志",
    "Settings": "设置",
    "Preferences": "偏好设置",
    "Defaults": "默认值",
    "Overrides": "覆盖",
    "Fallbacks": "回退",
    "Aliases": "别名",
    "Shortcuts": "快捷方式",
    
    # 页面特定标题
    "WhatsApp (web channel)": "WhatsApp（网页通道）",
    "Discord (bot channel)": "Discord（机器人频道）",
    "Slack (Socket Mode / OAuth App)": "Slack（Socket 模式 / OAuth 应用）",
    "iMessage (macOS-only)": "iMessage（仅限 macOS）",
    "Signal (signal-cli bridge)": "Signal（signal-cli 桥接）",
    "Mattermost (plugin)": "Mattermost（插件）",
    "WhatsApp FAQ: sending messages + pairing": "WhatsApp 常见问题：发送消息 + 配对",
    "Group-ish threads (`is_group=false`)": "类群组线程（is_group=false）",
    
    # 更多英文标题
    "The number model (important)": "号码模式（重要）",
    "External daemon mode (httpUrl)": "外部守护进程模式（httpUrl）",
    "Typing + read receipts": "输入提示 + 已读回执",
    "Reactions (message tool)": "反应（消息工具）",
    "Plugin required": "需要插件",
    "Environment variables (default account)": "环境变量（默认账户）",
    "Chat modes": "聊天模式",
    "Access control (DMs)": "访问控制（私信）",
    "Channels (groups)": "频道（群组）",
    "Targets for outbound delivery": "出站发送目标",
    "Multi-account": "多账户",
    "Error codes": "错误代码",
    "Gateway daemon (systemd / launchd)": "网关守护进程（systemd / launchd）",
    "Node execution (system.run)": "节点执行 (system.run)",
    "Dynamic skills (watcher / remote node)": "动态技能（watcher / 远程节点）",
    "find ~ event": "`find ~` 事件",
    "Lock down gateway WebSocket (local auth)": "锁定网关 WebSocket（本地认证）",
    "Example: no filesystem/shell access (allow provider messaging)": "示例：无文件系统/shell 访问（允许提供商消息传递）",
    "Secret scanning (detect-secrets)": "秘密扫描 (detect-secrets)",
    "Option 1: Using reverse proxy + Let's Encrypt (recommended)": "方案一：使用反向代理 + Let's Encrypt（推荐）",
    "Option 2: Using Openclaw built-in TLS": "方案二：使用 Openclaw 内置 TLS",
    "Step 1: Install Nginx and Certbot": "步骤 1：安装 Nginx 和 Certbot",
    "Step 2: Configure Nginx reverse proxy": "步骤 2：配置 Nginx 反向代理",
    "Step 3: Request Let's Encrypt certificate": "步骤 3：申请 Let's Encrypt 证书",
    "Step 4: Configure Openclaw": "步骤 4：配置 Openclaw",
    "Pairing (mobile)": "配对（移动端）",
    "Pairing (headless)": "配对（无头模式）",
    "Pairing workflow": "配对工作流程",
    "Approve workflow": "审批工作流程",
    "Session storage": "会话存储",
    "Session keys": "会话密钥",
    "Multi-session": "多会话",
    "Daemon mode": "守护进程模式",
    "Foreground mode": "前台模式",
    "Background mode": "后台模式",
    "Startup options": "启动选项",
    "Shutdown options": "关闭选项",
    "Restart options": "重启选项",
    "Health check": "健康检查",
    "Status check": "状态检查",
    "Log files": "日志文件",
    "Log levels": "日志级别",
    "Log rotation": "日志轮转",
    "Debug mode": "调试模式",
    "Verbose mode": "详细模式",
    "Quiet mode": "安静模式",
    "Dry run": "试运行",
    "Force mode": "强制模式",
    "Interactive mode": "交互模式",
    "Non-interactive mode": "非交互模式",
    "Batch mode": "批处理模式",
    "Single mode": "单一模式",
    "Cluster mode": "集群模式",
    "Standalone mode": "独立模式",
    "Embedded mode": "嵌入模式",
    "External mode": "外部模式",
    "Internal mode": "内部模式",
    "Public mode": "公共模式",
    "Private mode": "私有模式",
    "Shared mode": "共享模式",
    "Exclusive mode": "独占模式",
    "Read mode": "读取模式",
    "Write mode": "写入模式",
    "Append mode": "追加模式",
    "Overwrite mode": "覆盖模式",
    "Create mode": "创建模式",
    "Update mode": "更新模式",
    "Delete mode": "删除模式",
    "Sync mode": "同步模式",
    "Async mode": "异步模式",
    "Blocking mode": "阻塞模式",
    "Non-blocking mode": "非阻塞模式",
    "Timeout": "超时",
    "Retry": "重试",
    "Fallback": "回退",
    "Default": "默认",
    "Custom": "自定义",
    "Standard": "标准",
    "Extended": "扩展",
    "Basic": "基础",
    "Advanced": "高级",
    "Expert": "专家",
    "Beginner": "初学者",
    "Intermediate": "中级",
    "Required": "必需",
    "Optional": "可选",
    "Deprecated": "已弃用",
    "Experimental": "实验性",
    "Stable": "稳定",
    "Beta": "测试版",
    "Alpha": "内测版",
    "Release": "发布版",
    "Development": "开发版",
    "Production": "生产环境",
    "Staging": "预发布环境",
    "Local": "本地",
    "Remote": "远程",
    "Cloud": "云端",
    "On-premise": "本地部署",
    "Hybrid": "混合",
    "Native": "原生",
    "Container": "容器",
    "Virtual": "虚拟",
    "Physical": "物理",
    "Managed": "托管",
    "Self-hosted": "自托管",
    "Hosted": "托管",
    "SaaS": "SaaS",
    "PaaS": "PaaS",
    "IaaS": "IaaS",
    
    "Config snippet": "配置片段",
    "What it does": "功能说明",
    "Related docs": "相关文档",
    "Gateway": "网关",
    "Concepts": "概念",
    "My Hook": "我的钩子",
    "Why hybrid?": "为什么选择混合模式？",
    "Main session jobs (system events)": "主会话任务（系统事件）",
    "Isolated jobs (dedicated cron sessions)": "隔离任务（专用 cron 会话）",
    "How we merge results (the current design)": "如何合并结果（当前设计）",
    "Gateway Canvas Host (recommended for web content)": "网关 Canvas 主机（推荐用于网页内容）",
    "Event Context": "事件上下文",
    "Where to get a setup-token": "从哪里获取 setup-token",
    "What gets indexed (and when)": "什么会被索引（以及何时）",
    "Vision: image send (attachment → multimodal message)": "视觉：图片发送（附件 → 多模态消息）",
    "Verify Eligibility": "验证资格",
    "Use a different model": "使用不同的模型",
    "Use Specific Event Keys": "使用特定事件键",
    "Unit / integration (default)": "单元/集成测试（默认）",
    "Test Hooks Directly": "直接测试钩子",
    "Tailnet (cross-network)": "Tailnet（跨网络）",
    "Single-agent mode (default)": "单代理模式（默认）",
    "Session memory search (experimental)": "会话记忆搜索（实验性）",
    "Schedules": "调度计划",
    "Recommended live recipes": "推荐的实时配方",
    "Per-Hook Configuration": "每个钩子的配置",
    "Payload shapes (what runs)": "有效载荷形状（运行内容）",
    "Optional: Local via LM Studio (manual)": "可选：通过 LM Studio 本地运行（手动）",
    "Onboarding": "入门引导",
    "Ollama": "Ollama",
    "New Config Format (Recommended)": "新配置格式（推荐）",
    "Modern smoke set (tool calling + image)": "现代冒烟测试集（工具调用 + 图片）",
    "Model and thinking overrides": "模型和思考覆盖",
    "Metadata Fields": "元数据字段",
    "Messages Not Triggering": "消息未触发",
    "Manual host/port": "手动指定主机/端口",
    "Main vs isolated execution": "主执行 vs 隔离执行",
    "Local embedding auto-download": "本地嵌入自动下载",
    "Live (real providers + real models)": "实时测试（真实提供商 + 真实模型）",
    "List Hooks": "列出钩子",
    "Legacy Config Format (Still Supported)": "旧配置格式（仍支持）",
    "Layer 2: Gateway + dev agent smoke (what \"@clawdbot\" actually does)": "第二层：网关 + 开发代理冒烟测试",
    "Layer 1: Direct model completion (no gateway)": "第一层：直接模型完成（无网关）",
    "Keep Handlers Fast": "保持处理器快速",
    "Jobs": "任务",
    "Hybrid search (BM25 + vector)": "混合搜索（BM25 + 向量）",
    "How the memory tools work": "记忆工具如何工作",
    "Hook Not Executing": "钩子未执行",
    "Hook Not Eligible": "钩子不符合条件",
    "Hook Not Discovered": "钩子未被发现",
    "Protocol typing and codegen": "协议类型和代码生成",
    "Prereqs": "前提条件",
    "Pre-compaction memory flush": "压缩前记忆刷新",
    "Per-Agent Sandbox and Tool Configuration": "每个代理的沙盒和工具配置",
    "Paths (quick map)": "路径（快速映射）",
    "Pairing + local trust": "配对 + 本地信任",
    "Operations snapshot": "操作快照",
    "One-time setup": "一次性设置",
    "Onboarding flow (typical)": "入门流程（典型）",
    "Offline regression (CI-safe)": "离线回归测试（CI 安全）",
    "Multiple agents = multiple people, multiple personalities": "多代理 = 多个人，多个个性",
    "Multiple accounts / phone numbers": "多账户/多电话号码",
    "Models registry (`models.json`)": "模型注册表（`models.json`）",
    "Model refs": "模型引用",
    "Model overview (M2.1)": "模型概述（M2.1）",
    "Migration Guide": "迁移指南",
    "Memory files (Markdown)": "记忆文件（Markdown）",
    "Mapping transports → session keys": "传输映射 → 会话密钥",
    "Local vs remote mode": "本地 vs 远程模式",
    "Live: model smoke (profile keys)": "实时：模型冒烟测试（配置键）",
    "Live: model matrix (what we cover)": "实时：模型矩阵（覆盖范围）",
    "Lifecycle": "生命周期",
    "Launchd control": "Launchd 控制",
    "Kimi Code": "Kimi 代码",
    "Invariants": "不变量",
    "Install": "安装",
    "Inspecting": "检查",
    "How model selection works": "模型选择如何工作",
    "Hook Structure": "钩子结构",
    "Hook Packs (npm/archives)": "钩子包（npm/归档）",
    "Hook Discovery": "钩子发现",
    "Getting Oriented": "入门指引",
    "Gateway is the source of truth": "网关是真实来源",
    "Expose the handler (advanced, unsupported)": "暴露处理器（高级，不支持）",
    "Exec approvals (system.run)": "执行审批（system.run）",
    "Example: same channel, one peer to Opus": "示例：同一频道，一个对等节点到 Opus",
    "Event Types": "事件类型",
    "Endpoints": "端点",
    "Enable": "启用",
    "Docs sanity": "文档健全性检查",
    "Discovery paths": "发现路径",
    "Deepgram live (audio transcription)": "Deepgram 实时（音频转录）",
    "Deep links": "深度链接",
    "Credentials (never commit)": "凭证（永不提交）",
    "Creating Custom Hooks": "创建自定义钩子",
    "Connection lifecycle (single client)": "连接生命周期（单客户端）",
    "Connection Runbook": "连接运维手册",
    "Configure via `clawdbot configure`": "通过 `clawdbot configure` 配置",
    "Configuration options": "配置选项",
    "Configuration (optional rename example)": "配置（可选重命名示例）",
    "Configuration (minimal)": "配置（最小）",
    "Config keys (overview)": "配置键（概述）",
    "Components and flows": "组件和流程",
    "Common errors": "常见错误",
    "Cleanup": "清理",
    "Choose a setup": "选择设置",
    "Built-in tools": "内置工具",
    "Build & dev workflow (native)": "构建和开发工作流（原生）",
    "Bootstrap files (injected)": "引导文件（注入）",
    "Beginner-friendly overview": "初学者友好概述",
    "Beginner quick path (VPS)": "初学者快速路径（VPS）",
    "Automatic memory flush (pre-compaction ping)": "自动记忆刷新（压缩前 ping）",
    "Auth": "认证",
    "Agent reliability evals (skills)": "代理可靠性评估（技能）",
    "Agent helper": "代理助手",
    "Adding regressions (guidance)": "添加回归测试（指南）",
    "View recent commands": "查看最近命令",
    "Verify hook is discovered": "验证钩子已被发现",
    "Verbose output (show missing requirements)": "详细输出（显示缺失的要求）",
    "Trigger the event": "触发事件",
    "Test import directly": "直接测试导入",
    "Switch or clear the agent on an existing job": "切换或清除现有任务的代理",
    "Show only eligible hooks": "仅显示符合条件的钩子",
    "Show eligibility summary": "显示资格摘要",
    "Show detailed info about a hook": "显示钩子的详细信息",
    "Session Management": "会话管理",
    "Send /new via your messaging channel": "通过消息通道发送 /new",
    "Pretty-print with jq": "使用 jq 美化打印",
    "Pin a job to agent \"ops\" (falls back to default if that agent is missing)": "将任务固定到代理 \"ops\"",
    "Other platforms": "其他平台",
    "Or pick a distro explicitly:": "或明确选择发行版：",
    "My Custom Hook": "我的自定义钩子",
    "Multi-Agent Routing": "多代理路由",
    "List all hooks": "列出所有钩子",
    "Hooks": "钩子",
    "Gateway architecture": "网关架构",
    "Filter by action": "按操作过滤",
    "Enable it": "启用它",
    "Enable a hook": "启用钩子",
    "Disable a hook": "禁用钩子",
    "Cookies": "Cookies",
    "Agent Runtime 🤖": "代理运行时 🤖",
    
    "Quick model picks (anecdotal)": "快速模型选择（经验之谈）",
    "Quick start": "快速开始",
    "Quick start (pair + connect)": "快速开始（配对 + 连接）",
    "Remote access": "远程访问",
    "Responses": "响应",
    "Routing rules (how messages pick an agent)": "路由规则（消息如何选择代理）",
    "Run the push handler": "运行推送处理器",
    "Send policy (optional)": "发送策略（可选）",
    "Session origin metadata": "会话来源元数据",
    "Session pruning": "会话修剪",
    "Setup wizard (recommended)": "设置向导（推荐）",
    "Start the watch": "启动监视",
    "Steering while streaming": "流式传输时的引导",
    "Storage & history": "存储与历史",
    "Support snapshot": "支持快照",
    "Switching models in chat (`/model`)": "在聊天中切换模型（`/model`）",
    "System control": "系统控制",
    "System control (systemd user unit)": "系统控制（systemd 用户单元）",
    "Test": "测试",
    "Test suites (what runs where)": "测试套件（在哪里运行什么）",
    "Tips": "提示",
    "Vector memory search": "向量记忆搜索",
    "Voice wake + talk mode": "语音唤醒 + 对话模式",
    'What is "one agent"?': '什么是"一个代理"？',
    "When to write memory": "何时写入记忆",
    "Where state lives": "状态存储位置",
    "Which suite should I run?": "我应该运行哪个套件？",
    "Wire protocol (summary)": "通信协议（摘要）",
    "Wizard (recommended)": "向导（推荐）",
    "Workspace (required)": "工作区（必需）",
    "Agent Events": "代理事件",
    "Aggregators / alternate gateways": "聚合器/替代网关",
    "Baseline: tool calling (Read + optional Exec)": "基线：工具调用（读取 + 可选执行）",
    "Bonjour (LAN)": "Bonjour（局域网）",
    "Canvas eval / snapshot": "Canvas 评估/快照",
    "Check Discovery": "检查发现",
    "Check Eligibility": "检查资格",
    "Check Registration": "检查注册",
    "Command Events": "命令事件",
    "Core Components": "核心组件",
    "DeepSeek": "DeepSeek",
    "Delivery (channel + target)": "发送（通道 + 目标）",
    "Discovery Flow": "发现流程",
    "Embedding cache": "嵌入缓存",
    "Enable Hook Logging": "启用钩子日志",
    "Enable/Disable": "启用/禁用",
    "Event Flow": "事件流程",
    "Extra Directories": "额外目录",
    "Filter Events Early": "提前过滤事件",
    "From Legacy Config to Discovery": "从旧配置到发现",
    "Future Events": "未来事件",
    "Gateway (daemon)": "网关（守护进程）",
    "Gateway Events": "网关事件",
    "Gateway Logs": "网关日志",
    "Gemini embeddings (native)": "Gemini 嵌入（原生）",
    "Handle Errors Gracefully": "优雅地处理错误",
    "Handler Errors": "处理器错误",
    "Handler Implementation": "处理器实现",
    "Hook Information": "钩子信息",
}


def translate_file():
    content = DOCS_FILE.read_text(encoding='utf-8')
    lines = content.split('\n')
    translated_count = 0
    
    for i, line in enumerate(lines):
        if not line.startswith('#'):
            continue
            
        original = line
        
        # 提取标题级别和内容
        match = re.match(r'^(#{1,6})\s+(.+)$', line)
        if not match:
            continue
            
        prefix = match.group(1)
        title = match.group(2).strip()
        
        # 移除末尾的 ]（如果有）
        title = re.sub(r'\s*\]$', '', title)
        
        # 查找精确匹配
        if title in TRANSLATIONS:
            lines[i] = f"{prefix} {TRANSLATIONS[title]}"
            translated_count += 1
            continue
        
        # 查找不区分大小写的匹配
        for eng, chn in TRANSLATIONS.items():
            if title.lower() == eng.lower():
                lines[i] = f"{prefix} {chn}"
                translated_count += 1
                break
    
    new_content = '\n'.join(lines)
    DOCS_FILE.write_text(new_content, encoding='utf-8')
    
    eng_headings = len([l for l in lines if l.startswith('#') and re.search(r'[a-z]{4,}', l, re.I)])
    
    print(f"翻译完成!")
    print(f"已翻译标题数: {translated_count}")
    print(f"剩余英文标题数: {eng_headings}")


if __name__ == '__main__':
    translate_file()
